name: app_links_deep_link_client
description: A Dart package which provides a deep link stream using app_links (Firebase App Links compatible)
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  deep_link_client:
    path: ../deep_link_client
  app_links: ^6.3.2
  equatable: ^2.0.3
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^6.0.0
